In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("VietJobs.csv")

print("Shape:", df.shape)
df.head()
df.info()

Shape: (48092, 18)
<class 'pandas.DataFrame'>
RangeIndex: 48092 entries, 0 to 48091
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            48092 non-null  str
 1   location             48092 non-null  str
 2   country              48092 non-null  str
 3   qualifications       47722 non-null  str
 4   technical_skills     41655 non-null  str
 5   soft_skills          45451 non-null  str
 6   languages_required   12296 non-null  str
 7   experience_required  48092 non-null  str
 8   salary               48092 non-null  str
 9   contract_type        48092 non-null  str
 10  working_hours        43110 non-null  str
 11  benefits             48053 non-null  str
 12  description          48092 non-null  str
 13  requirements_text    48083 non-null  str
 14  category             48092 non-null  str
 15  salary_min           48092 non-null  int64
 16  salary_max           48092 non-null  int64
 17  salary_avg           48092 non-null  str
dtypes: int64(2), str(16)
memory usage: 6.6 MB

In [ ]:
df.head()

In [5]:
df_dn = df[df["location"].str.contains("đà nẵng", case=False, na=False)]

In [8]:
df_dn

,job_title,location,country,qualifications,technical_skills,soft_skills,languages_required,experience_required,salary,contract_type,working_hours,benefits,description,requirements_text,category,salary_min,salary_max,salary_avg
29,Nhân Viên An Toàn Lao Động,đà nẵng,Việt Nam,['Tốt nghiệp chuyên ngành Bảo Hộ Lao Động hoặc...,"['Word', 'Excel', 'Power Point', 'phần mềm liê...","['Kỹ năng giao tiếp', 'làm việc nhóm', 'chịu đ...",NaN,1 năm,0.0 triệu,Toàn thời gian,NaN,"['Thưởng lễ, Tết, thưởng đợt, quyết toán', 'Đi...","Lập kế hoạch, thực hiện và giám sát các hoạt đ...",Tốt nghiệp chuyên ngành Bảo Hộ Lao Động hoặc C...,nông_nghiệp_năng_lượng_môi_trường,0,0,Thoả thuận
132,Chuyên Viên HSE,đà nẵng,Việt Nam,['Tốt nghiệp Đại học chuyên ngành kỹ thuật'],"['Kiểm tra và đánh giá rủi ro', 'Kiến thức về ...","['Trung thực', 'Cẩn thận']",tiếng anh,1 năm,12.0 - 15.0 triệu,Toàn thời gian,Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),"['Mức lương cạnh tranh', 'Các khoản hỗ trợ khá...","Đề xuất, tổ chức, thực hiện các nhiệm vụ để đả...",Tốt nghiệp Đại học chuyên ngành kỹ thuật. Tối ...,nông_nghiệp_năng_lượng_môi_trường,12,15,13 triệu
178,Nhân Viên Môi Trường,đà nẵng,Việt Nam,"['Tốt nghiệp kỹ sư môi trường', 'Cấp thoát nước']","['Xử lý nước thải', 'Nước cấp']","['Giám sát', 'Quản lý dự án']",NaN,2 năm,10.0 - 18.0 triệu,Toàn thời gian,Thứ 2 - Thứ 7 (từ 07:30 đến 17:00),"['Bảo hiểm xã hội', 'Bảo hiểm sức khỏe', 'Khám...","Khảo sát, lên phương án công nghệ, biện pháp t...","Tốt nghiệp kỹ sư môi trường, cấp thoát nước. C...",nông_nghiệp_năng_lượng_môi_trường,10,18,14 triệu
224,Kỹ Sư An Toàn,đà nẵng,Việt Nam,['Cao Đẳng trở lên'],"['MS Word', 'Excel', 'Power Point']","['Giải quyết tình huống', 'Tạo dựng mối quan h...",NaN,1 năm,10.0 - 14.0 triệu,Toàn thời gian,Thứ 2 - Thứ 7 (từ 07:30 đến 17:30),"['Phụ cấp theo tính chất công việc', 'Xét tăng...",Giám sát việc lắp đặt hệ thống hạ tầng: hàng r...,Có kiến thức trong lĩnh vực an toàn như: Xây d...,nông_nghiệp_năng_lượng_môi_trường,10,14,12 triệu
251,Kỹ Sư Hiện Trường/ Ks An Toàn Lao Động,đà nẵng,Việt Nam,"['Tốt nghiệp đại học, chuyên ngành xây dựng dâ...",NaN,NaN,NaN,3 năm,0.0 triệu,Toàn thời gian,NaN,"['Được tham gia đầy đủ chế độ BHXH, BHYT, BHTN...","- Theo dõi quá trình thi công công trình, bám ...","- Tốt nghiệp đại học, chuyên ngành xây dựng dâ...",nông_nghiệp_năng_lượng_môi_trường,0,0,Thoả thuận
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47925,Kế Toán Thủ Quỹ-Ngân Hàng,đà nẵng,Việt Nam,"['Tốt nghiệp cao đẳng, đại học chuyên ngành kế...",['Thành thạo sử dụng vi tính văn phòng'],"['cẩn thận', 'trung thực', 'nhiệt tình']",NaN,1 năm,0.0 triệu,Toàn thời gian,Thứ 2 - Thứ 6 (từ 07:30 đến 17:00)\nThứ 7 (từ ...,"['Tham gia BHXH, BHYT, BHTN', 'Hỗ trợ ăn cơm t...",* Theo dõi thu chi nội bộ.\n * Thực hiện cá...,"* Ý thức: cẩn thận, trung thực, nhiệt tình\n...",tài_chính_kế_toán_ngân_hàng_bảo_hiểm,0,0,Thoả thuận
47943,Kế Toán Kho,"hồ chí minh, đà nẵng",Việt Nam,"['Tốt nghiệp Trung cấp, Cao đẳng trở lên ( chu...","['word', 'excel', 'email']","['khả năng thích ứng với công việc nhanh', 'bi...",NaN,2 năm,10.0 - 12.0 triệu,Toàn thời gian,NaN,"['Bảo hiểm xã hội', 'Du lịch hàng năm', 'Thưởn...",- In phiếu xuất kho \n- Tổng hợp dữ liệu hàng ...,"- Tốt nghiệp Trung cấp, Cao đẳng trở lên ( chu...",tài_chính_kế_toán_ngân_hàng_bảo_hiểm,10,12,11 triệu
47963,Chuyên Viên Khách Hàng Doanh Nghiệp,đà nẵng,Việt Nam,['Tốt nghiệp Đại học chính quy trở lên chuyên ...,NaN,['Giao tiếp tốt'],NaN,1 năm,15.0 - 25.0 triệu,Toàn thời gian,Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),['Thu nhập hấp dẫn cùng gói phúc lợi toàn diện...,* Lên kế hoạch và triển khai công tác kinh d...,* Tốt nghiệp Đại học chính quy trở lên chuyê...,tài_chính_kế_toán_ngân_hàng_bảo_hiểm,15,25,20 triệu
48010,Chuyên Viên Quản Lý Đối Tác (Lĩnh Vực Vận Tải),đà nẵng,Việt Nam,"['Tốt nghiệp Đại học, ưu tiên các chuyên ngành...","['Thành thạo tin học văn phòng (Word, Excel, P...","['Kỹ năng đàm phán, thuyết trình và giao tiếp ...",tiếng anh,1 năm,0.0 triệu,Toàn thời gian,Thứ 2 - Thứ 6 (từ 08:00 đến 17:30),"['Mức lương thỏa thuận theo năng lực, đánh giá...","* Tìm kiếm, phát triển mới các Đối tác lĩnh ...","* Tốt nghiệp Đại học, ưu tiên các chuyên ngà...",tài_chính_kế_toán_ngân_hàng_bảo_hiểm,0,0,Thoả thuận
48032,Digital Marketing Mạnh Google Ads (Đi Làm Ngay),"hồ chí minh, đà nẵng",Việt Nam,"['Tốt nghiệp chuyên ngành Marketing, Truyền th...",['Google Ads'],"['Kỹ năng phân tích dữ liệu', 'tư duy logic', ...",NaN,1 năm,15.0 - 20.0 triệu,Toàn thời gian,NaN,"['đóng BHXH', 'thưởng các ngày lễ lớn trong nă...",* Lập kế hoạch và triển khai chiến dịch quản...,* Ưu tiên: Ứng viên có kinh nghiệm trong ngà...,tài_chính_kế_toán_ngân_hàng_bảo_hiểm,15,20,17 triệu

In [11]:
print("Rows in Da Nang:", len(df_dn))
df_dn["category"].unique()

Rows in Da Nang: 1089

<StringArray>
[               'nông_nghiệp_năng_lượng_môi_trường',
               'du_lịch_nhà_hàng_khách_sạn_dịch_vụ',
        'marketing_truyền_thông_quảng_cáo_nội_dung',
               'nhân_sự_hành_chính_pháp_chế_tư_vấn',
             'tài_chính_kế_toán_ngân_hàng_bảo_hiểm',
                              'ngôn_ngữ_dịch_thuật',
                      'giáo_dục_đào_tạo_nghiên_cứu',
                 'logistics_vận_tải_chuỗi_cung_ứng',
                  'công_nghệ_thông_tin_kỹ_thuật_số',
                  'xây_dựng_kiến_trúc_bất_động_sản',
          'kinh_doanh_bán_hàng_chăm_sóc_khách_hàng',
 'thiết_kế_nghệ_thuật_giải_trí_truyền_hình_báo_chí',
               'sản_xuất_lao_động_phổ_thông_cơ_khí',
   'y_tế_dược_chăm_sóc_sức_khỏe_công_nghệ_sinh_học',
                                   'nhóm_nghề_khác',
                 'kỹ_thuật_điện_điện_tử_viễn_thông']
Length: 16, dtype: str

In [20]:
pd.reset_option("display.max_colwidth")

df[df["category"] == "kỹ_thuật_điện_điện_tử_viễn_thông"]

,job_title,location,country,qualifications,technical_skills,soft_skills,languages_required,experience_required,salary,contract_type,working_hours,benefits,description,requirements_text,category,salary_min,salary_max,salary_avg
43746,Phó Giám Đốc_Ngành MEP - Cơ Điện,hồ chí minh,Việt Nam,['Tốt nghiệp Đại học chính quy chuyên ngành Đi...,"['Autocad', 'Microsoft Project', 'vi tính văn ...","['Khả năng làm việc độc lập', 'sáng tạo', 'kỹ ...",tiếng anh,5 năm,0.0 triệu,Toàn thời gian,Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),"['Các chế độ phúc lợi (du lịch, khám sức khỏe ...",Điều phối tổng thể hoạt động các dự án từ lúc ...,Tốt nghiệp Đại học chính quy chuyên ngành Điện...,kỹ_thuật_điện_điện_tử_viễn_thông,0,0,Thoả thuận
43747,Chuyên Viên Kinh Doanh Thang Máy,hồ chí minh,Việt Nam,['Trung cấp trở lên'],"['Kỹ năng giao tiếp', 'Kỹ năng chốt sale', 'Ki...","['Giải quyết vấn đề', 'Làm việc nhóm hiệu quả'...",NaN,1 năm,20.0 - 40.0 triệu,Toàn thời gian,Thứ 2 - Thứ 7 (từ 08:00 đến 17:00),"['Bảo hiểm xã hội', 'Bảo hiểm y tế', 'Bảo hiểm...",Xây dựng và phát triển nguồn data các đối tác ...,"Nam, tuổi từ 20 trở lên. Kinh nghiệm từ 1 năm ...",kỹ_thuật_điện_điện_tử_viễn_thông,20,40,30 triệu
43748,Sales Leader - Trưởng Khu Vực Kinh Doanh Thang...,hồ chí minh,Việt Nam,['Trung cấp trở lên'],"['Kỹ năng bán hàng', 'Kỹ năng quản lý đội nhóm']","['Kỹ năng giao tiếp', 'Giải quyết vấn đề', 'Là...",NaN,2 năm,25.0 - 50.0 triệu,Toàn thời gian,Thứ 2 - Thứ 7 (từ 08:00 đến 17:00),"['Bảo hiểm xã hội', 'Khám sức khỏe định kỳ', '...",1. Đảm bảo tiêu chí mục tiêu kế hoạch của nhóm...,"Nam, tuổi từ 25 trở lên. Kinh nghiệm từ 02 năm...",kỹ_thuật_điện_điện_tử_viễn_thông,25,50,37 triệu
43749,Triển Khai Phần Mềm,hà nội,Việt Nam,['Đại Học trở lên'],NaN,"['Kỹ năng giao tiếp', 'Khả năng làm việc tập t...",NaN,6 tháng,8.0 - 20.0 triệu,Toàn thời gian,8h00 – 12h00 và 13h30 – 17h30 (Thứ 2 – Thứ 6),"['Thưởng hiệu suất công việc', 'Thưởng dự án',...",Triển khai các hệ thống phần mềm phục vụ ngành...,Ứng viên đã có kinh nghiệm triển khai phần mềm...,kỹ_thuật_điện_điện_tử_viễn_thông,8,20,14 triệu
43750,Thiết Kế Điện - Tự Động Hóa (Tủ Máng Cáp Điện),hồ chí minh,Việt Nam,['Đại Học trở lên'],"['AutoCAD', 'Revit', 'Vi tính văn phòng']",NaN,NaN,3 năm,18.0 - 25.0 triệu,Toàn thời gian,"Thứ 2 - Thứ 6 (từ 08:30 đến 17:30), Thứ 7 làm ...","['Trợ cấp tiền điện thoại', 'Trợ cấp nhà ở tại...",Tiến hành kiểm tra và khảo sát hiện trường để ...,"Vi tính văn phòng tốt, AutoCAD khá, Revit khá,...",kỹ_thuật_điện_điện_tử_viễn_thông,18,25,21 triệu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44977,Trợ Lý Dự Án (Chỉ Tuyển Nữ - Ưu Tiên Dưới 25 T...,hà nội,Việt Nam,"['Trình độ trung cấp/cao đẳng', 'Ưu tiên các ứ...",NaN,"['Kỹ năng lập báo cáo', 'Giao tiếp', 'Thuyết t...",NaN,Không yêu cầu,0.0 triệu,Toàn thời gian,Thời gian hành chính: Từ thứ 2 đến thứ 6 hàng ...,"['Thu nhập hấp dẫn cạnh tranh', 'Thưởng cuối n...",- Thực hiện hồ sơ đấu thầu liên quan đến lĩnh ...,"- Nữ, trình độ trung cấp/cao đẳng, ưu tiên các...",kỹ_thuật_điện_điện_tử_viễn_thông,0,0,Thoả thuận
44978,Chuyên Viên Kinh Doanh B2B,hồ chí minh,Việt Nam,"['Cao đẳng, Đại học chuyên ngành kinh doanh ho...","['Tin học văn phòng (Word, Excel, PowerPoint)']","['Kỹ năng giao tiếp', 'Thuyết trình', 'Tự tin'...",NaN,Không yêu cầu,8.0 - 30.0 triệu,Toàn thời gian,"Thứ 2 - Thứ 6 (từ 08:00 đến 17:30), Thứ 7 (từ ...","['Mức lương cạnh tranh', 'Chế độ bảo hiểm đầy ...","Tìm kiếm, tiếp cận và chăm sóc khách hàng tiềm...","Không yêu cầu kinh nghiệm, được đào tạo bài bả...",kỹ_thuật_điện_điện_tử_viễn_thông,8,30,19 triệu
44979,Nhân Viên Kinh Doanh Viễn Thông,bắc ninh,Việt Nam,"['Tốt nghiệp trung cấp trở lên, tất cả các chu...",NaN,"['Kỹ năng giao tiếp', 'Kỹ năng đàm phán']",NaN,Không yêu cầu,8.0 - 20.0 triệu,Toàn thời gian,Thứ 2 - Thứ 7 (từ 08:00 đến 17:30),"['Lương tháng 13', 'Thưởng tết', 'Thưởng kinh ...","Tìm kiếm thông tin, tiếp cận các khách hàng ti...","Nam/Nữ, tuổi từ 20-35. Tốt nghiệp trung cấp tr...",kỹ_thuật_điện_điện_tử_viễn_thông,8,20,14 triệu
44980,Nhân Viên Kinh Doanh - Dịch Vụ Viễn Thông,hồ chí minh,Việt Nam,"['Cao đẳng/Đại học chuyên ngành Kinh tế', 'Mar...","['Thành thạo vi tính văn phòng (Word, Excel, P...","['Kỹ năng giao tiếp', 'Đàm phán và thuyết phục...",NaN,1 năm,30.0 - 35.0 triệu,Toàn thời gian,"Thứ 2 - Thứ 6 (từ 08:00 đến 17:30), Thứ 2 - Th...","['Chế độ bảo hiểm xã hội', 'Bảo hiểm y tế', 'B...",Tìm kiếm khách hàng tiềm năng có nhu cầu sử dụ...,Tốt nghiệp Cao đẳng/Đại học chuyên ngành Kinh ...,kỹ_thuật_điện_điện_tử_viễn_thông,30,35,32 triệu
44981,Nhân Viên Kinh Doanh Dịch Vụ Viễn Thông,hồ chí minh,Việt Nam,"['Tốt nghiệp THPT', 'Trung Cấp trở lên']","['Kiến thức cơ bản về công nghệ thông tin', 'M...","['Kỹ năng giao tiếp', 'Đàm phán', 'Thuyết phục...",NaN,Không yêu cầu,15.0 - 20.0 triệu,Toàn thời gian,"Thứ 2 - Thứ 6 (08:00 - 17:00), Thứ 7 (08:00 - ...","['Lương cứng + hoa hồng', 'Thưởng quý', 'Thưởn...","Tư vấn, giải thích cho khách hàng về dịch vụ d...","Nam, tốt nghiệp THPT, Trung Cấp trở lên, tuổi ...",kỹ_thuật_điện_điện_tử_viễn_thông,15,20,17 triệu

In [22]:
pd.set_option("display.max_colwidth", None)
df.loc[
    df["category"] == "y_tế_dược_chăm_sóc_sức_khỏe_công_nghệ_sinh_học",
    ["description", "requirements_text"]
]

,description,requirements_text
40664,"Phụ trách các sản phẩm, ngành hành kinh doanh của công ty về hệ thống /thiết bị y tế được phân công như: hệ thống y tế, thiết bị phòng mổ, hồi sức, nội soi, kiểm soát nhiểm khuẩn... Thực hiện tư vấn kỹ thuật, thuyết trình/demo sản phẩm/giải pháp với khách hàng; Chuẩn bị hồ sơ kỹ thuật, hồ sơ chào giá, hồ sơ dự thầu cho các dự án, gói thầu của Công ty và các vấn đề liên quan tới sản phẩm ngành hàng phân công phụ trách; Phối hợp với bộ phận Kinh Doanh để tư vấn, lựa chọn giải pháp kỹ thuật, sản phẩm cho khách hàng; Thực hiện triển khai các công việc hỗ trợ kinh doanh đảm bảo đạt doanh số ngành hàng mục tiêu của Công ty; Chịu trách nhiệm dịch tài liệu sản phẩm, dự thảo các nội dung giới thiệu sản phẩm trên website, fanpage và các trang mạng xã hội của Công ty, catalog sản phẩm/ngành hàng phụ trách phục vụ cho mục đích bán hàng, marketing, quảng cáo sản phẩm; Lên đề nghị đặt hàng/đề nghị cung cấp hàng hóa, cân đối tồn kho để chuyển Phòng Kế toán và Mua hàng đặt hàng cho hợp đồng/dự án đảm bảo tính phù hợp, chính xác, kịp thời.","Tốt nghiệp Đại học các ngành Điện tử y sinh, Kỹ thuật y sinh, công nghệ sinh học… Có ít nhất 01 năm kinh nghiệm tại các công ty Thiết bị y tế ở vị trí tương tự. Ưu tiên các ứng viên có kiến thức và kinh nghiệm về thiết bị phòng mổ, hồi sức. Tiếng Anh đọc dịch tài liệu chuyên ngành tốt, nghe nói viết thành thạo để trao đổi với chuyên gia/KH nước ngoài và tham gia các khóa đào tạo bằng tiếng Anh. Kỹ năng soạn thảo văn bản, thuyết trình tốt. Khả năng phân tích, luận chứng-chứng minh, tư duy sáng tạo-logic, chịu áp lực cao trong công việc. Giao tiếp tốt, chủ động, tận tâm, trách nhiệm trong công việc, có khả năng giải quyết công việc với cường độ cao, tiến độ gấp khi cần. Thái độ làm việc tốt, sẵn sàng tăng ca để hoàn thành dự án."
40665,"- Hình thức làm việc tự do, chủ động trong công việc\n- Chịu trách nhiệm chăm sóc, bán hàng cho các kênh bán hàng ETC trên địa bàn phụ trách (Data Khách Hàng Có Sẵn)\n- Giới thiệu sản phẩm đến: Các Bác sĩ, Dược sĩ,...trong bệnh viện và các phòng khám.\n- Quản lý và chăm sóc khách hàng của công ty\n- Tìm kiếm và mở rộng thị trường, tăng số lượng khách hàng mới tại địa bàn được giao.\n- Thu thập thông tin thị trường, đối thủ cạnh tranh.","- Tốt nghiệp Trung cấp, Cao đẳng trở lên các ngành nghề\n- Ưu tiên có kinh nghiệm lĩnh vực Phòng khám, Bệnh viện, Trình dược viên.\n- Giao tiếp tốt, có khả năng xây dựng quan hệ, thuyết phục khách hàng.\n- Nhanh nhẹn, chịu khó.\n- Có kỹ năng giao tiếp, kỹ năng đàm phán và khả năng thuyết phục.\n- Có khả năng tạo dựng mối quan hệ tốt với khách hàng."
40666,"Thực hiện công việc chuyên môn hàng ngày như: lĩnh thuốc, phát thuốc, tiêm thuốc, thay băng, đo mạch nhiệt độ huyết áp, đo điện tim, thụt tháo, thông tiểu, theo dõi bệnh nhân nặng ... theo sự phân công của Điều dưỡng trưởng Khoa. Thực hiện các y lệnh điều trị của BS nhanh chóng, đầy đủ và chính xác. Và các công việc khác theo sự phân công của lãnh đạo khoa.","Ưu tiên có CCHN. Sức khỏe tốt, giọng nói dễ nghe. Cẩn thận, tỉ mỉ, có trách nhiệm với công việc. Giao tiếp tốt."
40667,"- Phát triển sản phẩm\n- Tổ chức thực hiện kế hoạch trên (Khảo sát, Thúc đẩy dự án, CSKH)\n- Đôn đốc và Hỗ trợ sales tích cực thực hiện kế hoạch\n- Giám sát thực hiện kế hoạch phát triển sản phẩm\n- Quản lý nhóm nhân viên\n- Phối hợp các bộ phận khác giải quyết công việc\n- Báo cáo công việc cho cấp quản lý trực tiếp theo nhiệm vụ được giao.","- Tuổi: Từ 30 trở lên\n- Tốt nghiệp: Trung cấp/Cao đẳng và các ngành Y/Dược , điện tử y sinh, kỹ thuật y sinh, QTKD, chẩn đoán hình ảnh, xét nghiệm...\n- Kinh nghiệm làm việc: Ưu tiên các ứng viên có kinh nghiệm trong lĩnh vực thiết bị y tế và 02 năm ở vị trí tương đương\n- Có kiến thức và kỹ năng sales, marketing tốt, trung thực, nhanh nhẹn.\n- Có khả năng đàm phán, kỹ năng bán hàng hiệu quả.\n- Làm việc chủ động, có kế hoạch, khả năng đi công tác xa"
40668,". Lập kế hoạch & phát triển kinh doanh\n- Xây dựng chiến lược kinh doanh theo từng giai đoạn, đảm bảo đạt chỉ tiêu doanh thu.\n- Nghiên cứu thị trường, phân tích đối thủ cạnh tranh để đề xuất các giải pháp kinh doanh hiệu quả.\n- Phối hợp với bộ phận Marketing để triển khai các chiến dịch quảng bá dịch vụ.\n- Mở rộng và phát triển hệ thống khách hàng tiềm năng, đối tác chiến lược.\n**B. Quản lý và điều hành đội ngũ kinh doanh**\n- Đào tạo và phát triển đội ngũ nhân viên kinh doanh.\n- Thiết lập KPIs, giám sát và đánh giá hiệu quả làm việc của nhân viên.\n- Định hướng, xây dựng quy trình tư vấn, chăm sóc khách hàng chuyên nghiệp.\n- Tổ chức họp định kỳ để tổng kết, rút kinh nghiệm và nâng cao hiệu suất làm việc.\n**C. Quản lý doanh số & chăm sóc khách hàng**\n- Giám sát hiệu quả kinh doanh, tối ưu doanh thu từ khách hàng mới và khách hàng cũ.\n- Đề xuất các chương trình khuyến mãi, ưu đãi nhằm thu hút và giữ chân khách hàng.\n- Xây dựng chính sách chăm sóc khách hàng trước, trong và sau khi sử dụng dịch vụ.\n- Xử lý các khiếu nại, phản hồi của khách hàng một cách chuyên nghiệp.\n**D. Phát triển kênh kinh doanh online & offline**\n- Quản lý và tối ưu hoạt động bán hàng tại cơ sở và trên các nền tảng online (Facebook, Instagram, TikTok, Zalo, Website, v.v.).\n- Hỗ trợ triển khai chiến dịch quảng cáo, truyền thông, sự kiện ra mắt dịch vụ mới.\n- Phối hợp với đội ngũ marketing để tối ưu hóa chuyển đổi khách hàng.","Tốt nghiệp Đại học chuyên ngành Kinh tế, Quản trị kinh doanh, Marketing hoặc các ngành liên quan.\nCó tối thiểu 3- 5 năm kinh nghiệm ở vị trí quản lý kinh doanh trong ngành thẩm mỹ, spa, làm đẹp.\nKỹ năng lãnh đạo, đào tạo và quản lý đội nhóm hiệu quả.\nKỹ năng giao tiếp, thuyết phục, đàm phán và xử lý tình huống tốt.\nCó tư duy chiến lược, khả năng phân tích và nhạy bén với xu hướng thị trường."
...,...,...
41622,"- Lập kế hoạch và thực hiện việc cung ứng, bảo quản, cấp phát, sử dụng thuốc. Quản lý xuất nhập thuốc quản lý đặc biệt\n- Tổ chức thực hiện pha chế thuốc (thuốc cho chuyên khoa sơ sinh, chuyên khoa ung bướu và chuyên khoa khác khi có yêu cầu)\n- Thực hiện các hoạt động thông tin thuốc trong bệnh viện. Tư vấn về sử dụng thuốc an toàn, hợp lý cho Hội đồng thuốc và điều trị, cán bộ y tế và người bệnh.\n- Tham gia theo dõi, kiểm tra, giám sát việc kê đơn thuốc nội trú và ngoại trú nhằm đẩy mạnh việc sử dụng thuốc an toàn, hợp lý và hiệu quả. Thực hiện đánh giá việc sử dụng thuốc trong bệnh viện\n- Thực hiện một số nhiệm vụ khác khi được Trưởng khoa Dược yêu cầu.","- Bằng cấp: Tốt nghiệp đại học Dược (có bằng sau đại học là lợi thế)\n- Sử dụng thành thạo tin học văn phòng (word, excel, powerpoint)\n- Đọc, hiểu, tìm kiếm tài liệu chuyên môn bằng tiếng Anh (đối với Dược lâm sàng)\n- Có kinh nghiệm làm tại vị trí tương đương ít nhất 1 năm"
41623,"Giới thiệu, chào bán các sản phẩm vật liệu nha khoa, sản phẩm chăm sóc răng miệng tới phòng nha, nha sĩ; Tìm kiếm phát triển hệ thống khách hàng mới là các phòng khám nha khoa; nhà thuốc; Chăm sóc khách hàng cũ của Công ty một cách có hệ thống; Thực hiện các kế hoạch phát triển thị trường đã được phê duyệt; Nắm bắt rõ yêu cầu và có kế hoạch hoàn thành tốt các chỉ tiêu bán hàng từ công ty: Doanh số, độ bao phủ thị trưởng, sản phẩm... Phối hợp với bộ phận Marketing và các bộ phận khác nhằm đạt được mục tiêu kế hoạch, đồng thời mang lại sự hài lòng cho Khách hàng; Hoàn thành đầy đủ các báo cáo ngày, tuần, tháng theo sự chỉ đạo của cấp quản lý.","Tối thiểu 1 năm kinh nghiệm vị trí tương đương, ưu tiên các ứng viên đã từng làm việc tại phòng nha, công ty phân phối vật liệu nha khoa hoặc ngành vật tư y tế; Có tư duy sắp xếp tốt, nhanh nhẹn, cẩn thận, trung thực; Kỹ năng giao tiếp tốt; Chăm chỉ, có trách nhiệm trong công việc."
41624,"Giới thiệu, chào bán các sản phẩm vật liệu nha khoa, sản phẩm chăm sóc răng miệng tới phòng nha, nha sĩ; Tìm kiếm phát triển hệ thống khách hàng mới là các phòng khám nha khoa; nhà thuốc; Chăm sóc khách hàng cũ của Công ty một cách có hệ thống; Thực hiện các kế hoạch phát triển thị trường đã được phê duyệt; Nắm bắt rõ yêu cầu và có kế hoạch hoàn thành tốt các chỉ tiêu bán hàng từ công ty: Doanh số, độ bao phủ thị trưởng, sản phẩm... Phối hợp với bộ phận Marketing và các bộ phận khác nhằm đạt được mục tiêu kế hoạch, đồng thời mang lại sự hài lòng cho Khách hàng; Hoàn thành đầy đủ các báo cáo ngày, tuần, tháng theo sự chỉ đạo của cấp quản lý.","Tối thiểu 1 năm kinh nghiệm vị trí tương đương, ưu tiên các ứng viên đã từng làm việc tại phòng nha, công ty phân phối vật liệu nha khoa hoặc ngành vật tư y tế; Có tư duy sắp xếp tốt, nhanh nhẹn, cẩn thận, trung thực; Kỹ năng giao tiếp tốt; Chăm chỉ, có trách nhiệm trong công việc."
41625,"Tiếp nhận, giải đáp thắc mắc của khách hàng qua điện thoại, email, chat, fanpage hoặc trực tiếp. Hỗ trợ khách hàng trong quá trình sử dụng sản phẩm/dịch vụ, hướng dẫn thao tác khi cần thiết. Tiếp nhận, xử lý và theo dõi các khiếu nại của khách hàng, đảm bảo phản hồi kịp thời, thỏa đáng. Cập nhật thông tin khách hàng vào hệ thống phần mềm Kiot của công ty. Phối hợp với các phòng ban (Kinh doanh, Kế Toán, Kho vận…) để giải quyết các vấn đề phát sinh. Chủ động liên hệ chăm sóc khách hàng định kỳ, duy trì mối quan hệ lâu dài. Thu thập ý kiến, phản hồi từ khách hàng để đề xuất cải thiện sản phẩm/dịch vụ.","1. Trình độ học vấn: Tốt nghiệp trung cấp trở lên, Có ít nhất 6 tháng kinh nghiệm sale hoặc CSKH. 2. Kỹ năng: Thành thạo tin học văn phòng Word; Excel, Power Point, Có khả năng làm việc độc lập và làm việc theo nhóm, Kỹ năng giao tiếp, và đàm phán, thuyết phục tốt, giọng nói nhẹ nhàng truyền cảm, Khả năng phân tích, nắm bắt tâm lý khách tốt, Khả năng lập kế hoạch, tổ chức thực hiện."
41626,"Giới thiệu về Công ty Cổ phần Thiết bị Y tế Đức Tín\nVới hơn 15 năm kinh nghiệm, Công ty cổ phần trang thiết bị y tế Đức Tín là đơn vị tiên phong và dẫn đầu trong lĩnh vực cung cấp thiết bị và vật tư y tế tiêu hao tại Việt Nam. Chúng tôi là nhà phân phối độc quyền các sản phẩm vật tư kỹ thuật cao từ các nhà sản xuất hàng đầu thế giới ( Đức, Hà Lan, Thụy Sĩ, Nhật Bản, USA,...), cam kết mang đến các giải pháp y tế hiện đại, góp phần nâng cao chất lượng chăm sóc sức khỏe tại Việt Nam.\n\nTại sao chọn Đức Tín?\n· Môi trường làm việc chuyên nghiệp với đội ngũ nhân sự giàu kinh nghiệm và nhiệt huyết.\n· Cơ hội phát triển nghề nghiệp lâu dài, được đào tạo bài bản.\n· Sứ mệnh rõ ràng: Hỗ trợ các cơ sở y tế và đội ngũ y bác sĩ bằng những thiết bị hiện đại, góp phần nâng cao hiệu quả điều trị cho người bệnh.\n· Giá trị cốt lõi: Chất lượng – Chính trực – Đổi mới – Lấy khách hàng là trung tâm – Cam kết với cộng đồng.\n\nMô tả công việc: \n * Thực hiện và chịu trách nhiệm các hoạt động bán hàng và sản phẩm được giao.\n * Thu thập thông tin thị trường, tìm kiếm khách hàng mới, phát triển hệ thống kênh phân phối tại các bệnh viện.\n * Đảm bảo việc luân chuyển hàng hóa đáp ứng đầy đủ về số lượng và kích cỡ theo nhu cầu bệnh viện.\n * Hỗ trợ bộ phận Kế toán theo dõi và thúc đẩy công tác thu hồi công nợ tại các bệnh viện.\n * Thực hiện các công việc khác theo sự phân công của Ban giám đốc/quản lý trực tiếp.","Yêu cầu ứng viên\n * Tốt nghiệp CAO ĐẲNG trở lên\n * Có kinh nghiệm về lĩnh vực kinh doanh là một lợi thế\n * Giao tiếp tốt, có khả năng làm việc nhóm, kỹ năng thuyết trình và đàm phán.\n * Trung thực, chăm chỉ, có thái độ, tinh thần trách nhiệm cao."

In [ ]:
sample_df = df.sample(n=150, random_state=42)

sample_df.to_csv("sample_150.csv", index=False)